package com.restaurante01.api_restaurante.compartilhado.dominio.enums;

public enum GatilhoEvento {
    PEDIDO_CRIADO,       //DISPARA: BAIXAR_ESTOQUE_ASSOCIACAO, BAIXAR_ESTOQUE_PRODUTO, CONSUMIR_CUPOM
    PEDIDO_ENTREGUE,     //DISPARA: COMPUTAR_PONTUACAO_FIDELIDADE, CRIAR_AVALIACAO
    PEDIDO_CANCELADO,    //DISPARA: ESTORNAR_ESTOQUE_ASSOCIACAO, ESTORNAR_ESTOQUE_PRODUTO
    AVALIACAO_CONCLUIDA, //DISPARA: COMPUTAR_PONTUACAO_AVALIACAO_REALIZADA
    CLIENTE_CADASTRADO   //DISPARA: CRIAR_FIDELIDADE_CLIENTE
}
