package com.restaurante01.api_restaurante.compartilhado.dominio.enums;

public enum TipoEvento {
    COMPUTAR_PONTUACAO_FIDELIDADE,          //OCORRE QUANDO UM PEDIDO É ATUALIZADO PARA STATUS = ENTREGUE
    BAIXAR_ESTOQUE_ASSOCIACAO,              //OCORRE QUANDO UM PEDIDO É CRIADO/REALIZADO
    BAIXAR_ESTOQUE_PRODUTO,                 //OCORRE QUANDO UM PEDIDO É CRIADO/REALIZADO
    ESTORNAR_ESTOQUE_ASSOCIACAO,            //OCORRE QUANDO UM PEDIDO É ATUALIZADO PARA STATUS = CANCELADO
    ESTORNAR_ESTOQUE_PRODUTO,               //OCORRE QUANDO UM PEDIDO É ATUALIZADO PARA STATUS = CANCELADO
    CONSUMIR_CUPOM                          //OCORRE QUANDO UM PEDIDO É CRIADO COM UM CUPOM DEFINIDO
}
