package com.restaurante01.api_restaurante.compartilhado.dominio.enums;

public enum TipoEvento {
    BAIXAR_ESTOQUE_ASSOCIACAO,                  //OCORRE QUANDO UM PEDIDO É CRIADO/REALIZADO
    BAIXAR_ESTOQUE_PRODUTO,                     //OCORRE QUANDO UM PEDIDO É CRIADO/REALIZADO
    ESTORNAR_ESTOQUE_ASSOCIACAO,                //OCORRE QUANDO UM PEDIDO É ATUALIZADO PARA STATUS = CANCELADO
    ESTORNAR_ESTOQUE_PRODUTO,                   //OCORRE QUANDO UM PEDIDO É ATUALIZADO PARA STATUS = CANCELADO
    CONSUMIR_CUPOM,                             //OCORRE QUANDO UM PEDIDO É CRIADO COM UM CUPOM DEFINIDO
    CRIAR_AVALIACAO,                            //OCORRE QUANDO UM PEDIDO É ATUALIZADO com status para ENTREGUE
    COMPUTAR_PONTUACAO_AVALIACAO_REALIZADA,     //OCORRE QUANDO UM CLIENTE REALIZA A AVALIAÇÃO COMPLETA DE UM PEDIDO
    COMPUTAR_PONTUACAO_PEDIDO_ENTREGUE,         //OCORRE QUANDO UM CLIENTE REALIZA UM PEDIDO E O STATUS DO PEDIDO É ATUALIZADO PARA ENTREGUE
    CRIAR_FIDELIDADE_CLIENTE                    //OCORRE QUANDO UM NOVO CLIENTE É CADASTRADO NO SISTEMA
}
