-- 1. SEQUENCES
CREATE SEQUENCE copons_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE itens_pedido_seq START WITH 1 INCREMENT BY 50;

-- 2. TABELAS (Sem dependências de FK no CREATE)
CREATE TABLE avaliacoes (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                            pedido_id BIGINT NOT NULL,
                            cliente_id BIGINT NOT NULL,
                            status VARCHAR(255),
                            avaliacao VARCHAR(255),
                            numero_notificacao_cliente VARCHAR(255),
                            data_criacao TIMESTAMP NOT NULL,
                            data_expiracao TIMESTAMP NOT NULL,
                            nota_valor INT,
                            comentario_valor VARCHAR(255),
                            CONSTRAINT pk_avaliacoes PRIMARY KEY (id)
);

CREATE TABLE cardapios (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                           data_criacao TIMESTAMP NOT NULL,
                           data_atualizacao TIMESTAMP,
                           criado_por VARCHAR(255),
                           atualizado_por VARCHAR(255),
                           nome VARCHAR(100) NOT NULL,
                           descricao CLOB NOT NULL,
                           disponibilidade BOOLEAN NOT NULL,
                           dtinicio date NOT NULL,
                           dtfim date,
                           CONSTRAINT pk_cardapios PRIMARY KEY (id)
);

CREATE TABLE produtos (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                          data_criacao TIMESTAMP NOT NULL,
                          data_atualizacao TIMESTAMP,
                          criado_por VARCHAR(255),
                          atualizado_por VARCHAR(255),
                          nome VARCHAR(100) NOT NULL,
                          descricao CLOB NOT NULL,
                          preco DECIMAL(10, 2) NOT NULL,
                          qtd_atual INT NOT NULL,
                          disponibilidade BOOLEAN NOT NULL,
                          CONSTRAINT pk_produtos PRIMARY KEY (id)
);

CREATE TABLE pedidos (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                         data_criacao TIMESTAMP NOT NULL,
                         data_atualizacao TIMESTAMP,
                         criado_por VARCHAR(255),
                         atualizado_por VARCHAR(255),
                         status_pedido VARCHAR(255) NOT NULL,
                         cardapio_de_referencia BIGINT NOT NULL,
                         cliente_id BIGINT,
                         nome VARCHAR(255),
                         cpf VARCHAR(255),
                         telefone VARCHAR(255),
                         rua VARCHAR(255),
                         numero INT,
                         bairro VARCHAR(255),
                         cidade VARCHAR(255),
                         estado VARCHAR(255),
                         cep VARCHAR(255),
                         referencia VARCHAR(255),
                         valor_bruto DECIMAL NOT NULL,
                         desconto DECIMAL NOT NULL,
                         valor_total DECIMAL NOT NULL,
                         id_cupom BIGINT,
                         codigo_cupom VARCHAR(255),
                         valor_para_desconto DECIMAL,
                         regra_do_cupom SMALLINT,
                         regra_recorrencia SMALLINT,
                         CONSTRAINT pk_pedidos PRIMARY KEY (id)
);

CREATE TABLE itens_pedido (
                              id BIGINT NOT NULL,
                              pedido_id BIGINT NOT NULL,
                              id_produto BIGINT NOT NULL,
                              nome VARCHAR(255),
                              quantidade INT NOT NULL,
                              preco_unitario DECIMAL NOT NULL,
                              observacao VARCHAR(255),
                              CONSTRAINT pk_itens_pedido PRIMARY KEY (id)
);

CREATE TABLE cardapio_produto (
                                  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                  cardapio_id BIGINT NOT NULL,
                                  produto_id BIGINT NOT NULL,
                                  preco_customizado DECIMAL,
                                  qtd_customizada INT,
                                  desc_customizada VARCHAR(255),
                                  disp_customizada BOOLEAN,
                                  obs VARCHAR(255),
                                  CONSTRAINT pk_cardapio_produto PRIMARY KEY (id)
);

CREATE TABLE clientes (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                          name VARCHAR(255) NOT NULL,
                          senha VARCHAR(255) NOT NULL,
                          role VARCHAR(255),
                          conta_ativa BOOLEAN NOT NULL,
                          telefone VARCHAR(11) NOT NULL,
                          email VARCHAR(255),
                          cpf VARCHAR(255),
                          ponto_fidelidade INT NOT NULL,
                          rua VARCHAR(255),
                          numero INT,
                          bairro VARCHAR(255),
                          cidade VARCHAR(255),
                          estado VARCHAR(255),
                          cep VARCHAR(255),
                          complemento VARCHAR(255),
                          referencia VARCHAR(255),
                          CONSTRAINT pk_clientes PRIMARY KEY (id)
);

CREATE TABLE copons (
                        id BIGINT NOT NULL,
                        data_criacao TIMESTAMP NOT NULL,
                        data_atualizacao TIMESTAMP,
                        criado_por VARCHAR(255),
                        atualizado_por VARCHAR(255),
                        tipo_desconto SMALLINT NOT NULL,
                        quantidade INT NOT NULL,
                        valor_desconto DECIMAL NOT NULL,
                        valor_min_pedido DECIMAL NOT NULL,
                        valor_max_pedido DECIMAL NOT NULL,
                        recorrencia SMALLINT NOT NULL,
                        esta_ativo BOOLEAN NOT NULL,
                        valor VARCHAR(255),
                        data_ini date NOT NULL,
                        hora_ini time NOT NULL,
                        data_fim date NOT NULL,
                        hora_fim time NOT NULL,
                        CONSTRAINT pk_copons PRIMARY KEY (id)
);

CREATE TABLE item_pedido_avaliado (
                                      id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                      avaliacao_id BIGINT,
                                      item_pedido_id BIGINT,
                                      produto_id BIGINT,
                                      item_nota_valor INT,
                                      item_comentario_valor VARCHAR(255),
                                      CONSTRAINT pk_item_pedido_avaliado PRIMARY KEY (id)
);

CREATE TABLE operadores (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                            name VARCHAR(255) NOT NULL,
                            senha VARCHAR(255) NOT NULL,
                            role VARCHAR(255),
                            conta_ativa BOOLEAN NOT NULL,
                            email VARCHAR(255),
                            cpf VARCHAR(255),
                            CONSTRAINT pk_operadores PRIMARY KEY (id)
);

CREATE TABLE outbox_eventos (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                agregado_tipo VARCHAR(50) NOT NULL,
                                agregado_id BIGINT NOT NULL,
                                tipo VARCHAR(100) NOT NULL,
                                payload CLOB NOT NULL,
                                status VARCHAR(20) NOT NULL,
                                tentativas INT NOT NULL,
                                criado_em TIMESTAMP NOT NULL,
                                processado_em TIMESTAMP,
                                CONSTRAINT pk_outbox_eventos PRIMARY KEY (id)
);

-- 3. CONSTRAINTS (Sempre por último)
ALTER TABLE outbox_eventos ADD CONSTRAINT uc_5d7cb2c4dacfac643b478b01b UNIQUE (agregado_tipo, agregado_id, tipo);
ALTER TABLE cardapio_produto ADD CONSTRAINT uc_c65ddc0df3ee41263caeefa27 UNIQUE (cardapio_id, produto_id);
ALTER TABLE cardapio_produto ADD CONSTRAINT FK_CARDAPIO_PRODUTO_ON_CARDAPIO FOREIGN KEY (cardapio_id) REFERENCES cardapios (id);
ALTER TABLE cardapio_produto ADD CONSTRAINT FK_CARDAPIO_PRODUTO_ON_PRODUTO FOREIGN KEY (produto_id) REFERENCES produtos (id);
ALTER TABLE item_pedido_avaliado ADD CONSTRAINT FK_ITEM_PEDIDO_AVALIADO_ON_AVALIACAO FOREIGN KEY (avaliacao_id) REFERENCES avaliacoes (id);
ALTER TABLE itens_pedido ADD CONSTRAINT FK_ITENS_PEDIDO_ON_PEDIDO FOREIGN KEY (pedido_id) REFERENCES pedidos (id);