-- Tabela principal do aggregate Fidelidade
CREATE TABLE fidelidades (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cliente_id    BIGINT                                  NOT NULL,
    pontuacao_atual INT                                   NOT NULL DEFAULT 0,
    CONSTRAINT pk_fidelidades PRIMARY KEY (id),
    CONSTRAINT uc_fidelidades_cliente_id UNIQUE (cliente_id)
);

-- Histórico de pontuações (ElementCollection de RegistroPontuacao)
CREATE TABLE fidelidade_historico (
    fidelidade_id          BIGINT       NOT NULL,
    posicao                INT          NOT NULL,
    ultima_pontuacao_gerada INT         NOT NULL,
    motivo                 VARCHAR(255) NOT NULL,
    data_computacao        TIMESTAMP    NOT NULL,
    saldo_no_dia           INT          NOT NULL,
    CONSTRAINT pk_fidelidade_historico PRIMARY KEY (fidelidade_id, posicao),
    CONSTRAINT fk_fidelidade_historico_on_fidelidade FOREIGN KEY (fidelidade_id) REFERENCES fidelidades (id)
);
