CREATE TABLE cardapio (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(255) NOT NULL,
    descricao VARCHAR2(4000) NOT NULL,
    disponibilidade NUMBER(1) NOT NULL, -- boolean armazenado como 0 (false) ou 1 (true)
    dataInicio DATE NOT NULL,
    dataFim DATE NULL
);